version: 0.0
os: linux
files:
   - source: /
     destination: /var/www/dealvector
permissions:
   - object: /var/www/dealvector
     pattern: "**"
     owner: www-data
     group: www-data
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    
   AfterInstall:
    - location: deployment/jenkins_deploy.sh
      runas: www-data
